[project]
name = "git-semantic-version"
description = "A monorepo-friendly setuptools plugin for directory-scoped conventional commit versioning."
dependencies = ["GitPython"]
dynamic = ["version"]

[project.scripts]
git-semver = "git_semver:main"

[project.entry-points."setuptools.finalize_distribution_options"]
git_semver = "git_semver:set_semver"

[build-system]
requires = ["GitPython", "setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["git_semver"]
