monorepo_root = true

[monorepo]
config_roots = [
  "*",
  "controller/*",
  "site-manager/*",
]

[settings]
experimental = true
task.auto_infer = ["node"]
python.uv_venv_auto = "create|source"

[tools]
node = "latest"
python = "latest"
uv = "latest"

[tasks.clean-all]
run = { task = "//...:clean" }

[tasks.deploy-all]
run = { task = "//...:deploy" }

[tasks.format-all]
run = { task = "//...:format" }

[tasks.lint-all]
run = { task = "//...:lint" }

[tasks.build-all]
run = { task = "//...:build" }

[deps.npm]
auto = true

[deps.uv]
auto = true
run = "uv sync --all-packages"
