[project]
name = "openwrt-controller-workspace"
dependencies = [
  "generate-openapi-spec",
  "git-semantic-version",
]
dynamic = ["version"]

[dependency-groups]
dev = [
  "black>=26.5.1",
]

[tool.setuptools]
packages = []

[tool.uv]
package = false

override-dependencies = ["psycopg2; sys_platform == 'never'"]

[tool.uv.workspace]
members = ["tools/*", "site-manager/backend", "controller/backend"]

[tool.uv.sources]
git-semantic-version = { workspace = true }
generate-openapi-spec = { workspace = true }
