[project]
name = "openwrt-controller"
dependencies = [
  "aiortc",
  "fastapi[standard]",
  "httpx2",
  "netjsonconfig",
  "rpc-router",
  "sqlmodel",
]
dynamic = ["version"]

[build-system]
requires = ["git-semantic-version", "setuptools>=45"]
build-backend = "setuptools.build_meta"

[tool.fastapi]
entrypoint = "app.main:app"
