[project]
name = "openwrt-controller"
dependencies = [
    "aiortc",
    "fastapi[standard]",
    "httpx2",
    "netjsonconfig",
    "sqlmodel",
]
dynamic = ["version"]

[tool.fastapi]
entrypoint = "app.main:app"

[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools>=45",
  "git-semantic-version"
]
