"""add mfa

Revision ID: 0a618c79f31f
Revises: f9e971b2bcfe
Create Date: 2026-08-24 17:40:49.685845

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "0a618c79f31f"
down_revision: Union[str, Sequence[str], None] = "f9e971b2bcfe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "totp_configurations",
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "encrypted_secret",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("device_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["username"],
            ["users.username"],
        ),
        sa.PrimaryKeyConstraint("username", "id"),
    )
    op.drop_constraint(None, "auth_codes", type_="foreignkey")
    op.drop_constraint(None, "auth_codes", type_="foreignkey")
    op.create_foreign_key(
        None,
        "auth_codes",
        "remote_users",
        ["subject", "upstream_issuer"],
        ["subject", "provider"],
    )
    op.alter_column("sites", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "sites",
        "last_heartbeat",
        existing_type=sa.NUMERIC(),
        type_=sa.Float(),
        nullable=False,
    )
    op.alter_column(
        "users",
        "disabled",
        existing_type=sa.INTEGER(),
        type_=sa.Boolean(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "disabled",
        existing_type=sa.Boolean(),
        type_=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "sites",
        "last_heartbeat",
        existing_type=sa.Float(),
        type_=sa.NUMERIC(),
        nullable=True,
    )
    op.alter_column("sites", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_constraint(None, "auth_codes", type_="foreignkey")
    op.create_foreign_key(
        None, "auth_codes", "remote_users", ["upstream_issuer"], ["provider"]
    )
    op.create_foreign_key(None, "auth_codes", "remote_users", ["subject"], ["subject"])
    op.drop_table("totp_configurations")
    # ### end Alembic commands ###
