"""initial db when alembic added

Revision ID: b4c185278af4
Revises:
Create Date: 2026-08-24 16:25:20.341138

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4c185278af4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sites",
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_heartbeat", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("site_id"),
    )
    op.create_table(
        "users",
        sa.Column(
            "username", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.Column(
            "permissions", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "hashed_password",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("username"),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column(
            "username", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "upstream_issuer",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column(
            "upstream_session",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column("expires", sa.DateTime(), nullable=False),
        sa.Column("jwt_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["username"],
            ["users.username"],
        ),
        sa.PrimaryKeyConstraint("jwt_id"),
    )
    op.create_table(
        "remote_users",
        sa.Column(
            "subject", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("link_authorized", sa.Boolean(), nullable=False),
        sa.Column(
            "linked_username",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["linked_username"],
            ["users.username"],
        ),
        sa.PrimaryKeyConstraint("subject", "provider"),
    )
    op.create_table(
        "siteaccessrelationship",
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column(
            "username", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.site_id"],
        ),
        sa.ForeignKeyConstraint(
            ["username"],
            ["users.username"],
        ),
        sa.PrimaryKeyConstraint("site_id", "username"),
    )
    op.create_table(
        "auth_codes",
        sa.Column(
            "secret", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "subject", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("expires", sa.DateTime(), nullable=False),
        sa.Column(
            "upstream_issuer",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column(
            "upstream_session",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["subject", "upstream_issuer"],
            ["remote_users.subject", "remote_users.provider"],
        ),
        sa.PrimaryKeyConstraint("secret"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("auth_codes")
    op.drop_table("siteaccessrelationship")
    op.drop_table("remote_users")
    op.drop_table("refresh_tokens")
    op.drop_table("users")
    op.drop_table("sites")
    # ### end Alembic commands ###
