"""add inform history

Revision ID: f9e971b2bcfe
Revises:
Create Date: 2026-08-24 13:21:20.468771

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f9e971b2bcfe"
down_revision: Union[str, Sequence[str], None] = "b4c185278af4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outages",
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("outage_start", sa.Float(), nullable=False),
        sa.Column("outage_end", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.site_id"],
        ),
        sa.PrimaryKeyConstraint("site_id", "outage_start"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("outages")
    # ### end Alembic commands ###
