[tasks.dev]
run = "fastapi dev --host 0.0.0.0 --port 8001"

[tasks.build]
run = "uv build --sdist"

[tasks.deploy]
run = "fastapi deploy"

[tasks.clean]
run = "rm -rf openapi.json openwrt_site_manager.egg-info PKG-INFO dist -r"

[tasks.format]
run = "uv run black app"

[tasks.generate-openapi-spec]
run = "python -m gen_openapi"
