[project]
name = "openwrt-site-manager"
dependencies = [
    "authlib",
    "fastapi[standard]",
    "httpx2",
    "itsdangerous",
    "joserfc",
    "pwdlib[argon2]",
    "pyjwt",
    "sqlmodel",
    "psycopg2",
    "logfire[fastapi,httpx,sqlalchemy]",
]
dynamic = ["version"]

[tool.fastapi]
entrypoint = "app.main:app"

[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools>=45",
  "git-semantic-version",
]
