[project]
name = "rpc-router"
dependencies = []
dynamic = ["version"]

[dependency-groups]
fastapi = ["fastapi"]
websockets = ["websockets"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv]
package = true

[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools>=45",
  "git-semantic-version"
]
