name: Deploy to FastAPI Cloud
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: |
          npm i
          uv sync --all-packages
      - name: Build
        run:  mise run build-all
      - name: Deploy
        run: |
          cd site-manager/backend
          cp -r ../frontend/dist .
          uv build --sdist
          cp openwrt_site_manager.egg-info/PKG-INFO .
          uv run fastapi deploy
        env:
          FASTAPI_CLOUD_TOKEN: ${{ secrets.FASTAPI_CLOUD_TOKEN }}
          FASTAPI_CLOUD_APP_ID: ${{ secrets.FASTAPI_CLOUD_APP_ID }}
