name: Deploy to FastAPI Cloud
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v7
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - uses: actions/setup-python@v5
        with:
          python-version: '3.14'
          cache: 'pip'
      - name: Install build deps
        run: |
          npm i -g mise
          uv sync --all-packages
      - name: Build
        run: npx mise run build-all
      - name: Deploy
        run: |
          cd site-manager/backend
          pip install build
          python -m build --sdist
          cp openwrt_site_manager.egg-info/PKG-INFO .
          uv run fastapi deploy
        env:
          FASTAPI_CLOUD_TOKEN: ${{ secrets.FASTAPI_CLOUD_TOKEN }}
          FASTAPI_CLOUD_APP_ID: ${{ secrets.FASTAPI_CLOUD_APP_ID }}
