name: Publish and Deploy
on:
  push:
    branches: [master]
permissions:
  id-token: write
  contents: read
  packages: write
env:
  FASTAPI_CLOUD_TOKEN: ${{ secrets.FASTAPI_CLOUD_TOKEN }}
  FASTAPI_CLOUD_APP_ID: ${{ secrets.FASTAPI_CLOUD_APP_ID }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
jobs:
  publish_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Get previous SHA
        id: sha
        run: |
          BEFORE_SHA="${{ github.event.before }}"
          ZERO_SHA="0000000000000000000000000000000000000000"

          if [ "$BEFORE_SHA" = "$ZERO_SHA" ] || ! git cat-file -e "$BEFORE_SHA" 2>/dev/null; then
            echo "Before SHA ($BEFORE_SHA) is missing or invalid (likely a force push or new branch)."
            BEFORE_SHA=$(git rev-parse HEAD~1)
          fi
          echo "before=$BEFORE_SHA" >> $GITHUB_OUTPUT
      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}
      - name: Disable Cross-Repository Blob Mounts
        run: |
          mkdir -p ~/.config/containers
          cat <<EOF > ~/.config/containers/registries.conf
          [[registry]]
          location = "ghcr.io"
          blocked = false
          # Forcing standard compression disables remote layer linking
          EOF
      - uses: jdx/mise-action@v4
        with:
          version: 2026.9.2
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install podman
        run: sudo apt-get update && sudo apt-get install -y podman
      - name: Start Podman Socket
        run: |
          systemctl --user enable --now podman.socket
          # Point your environment variables to the created socket if needed
          echo "DOCKER_HOST=unix://$XDG_RUNTIME_DIR/podman/podman.sock" >> $GITHUB_ENV
      - name: Format
        run: mise run //...:format
      - name: Build
        run: mise run //...:build
      - name: Publish
        run: mise run --continue-on-error //...:publish
      - name: Deploy
        run: mise run //...:deploy
