name: Publish and Deploy
on:
  push:
    branches: [master]
permissions:
  id-token: write
env:
  FASTAPI_CLOUD_TOKEN: ${{ secrets.FASTAPI_CLOUD_TOKEN }}
  FASTAPI_CLOUD_APP_ID: ${{ secrets.FASTAPI_CLOUD_APP_ID }}
jobs:
  publish_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@v4
        with:
          version: 2026.9.2
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Format
        run: mise run //...:format
      - name: Build
        run: mise run //...:build
      - name: Publish
        run: mise run --affected //...:publish
      - name: Deploy
        run: mise run //...:deploy
